version: "3"
services:
  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: gitjupalza
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3306:3306

  redis:
    image: redis
    ports:
      - 6379:6379

  gitjupalza:
    environment:
      REDIS_URL: redis
      REDIS_PORT: 6379
      MYSQL_URL: jdbc:mysql://mysql:3306/gitjupalza
      MYSQL_PASSWORD: root
      MYSQL_USERNAME: root
      SPRING_PROFILE: ${SPRING_PROFILE}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
    build: .
    ports:
      - 8080:8080
    depends_on:
      - mysql
      - redis